language: node_js
node_js:
- node
before_script:
- npm install -g mocha
script: mocha
deploy:
  provider: heroku
  api_key:
    secure: hTMeKNvXKtVCpLWLTgrAMH8cbTeRxaqbRTZb03KtLngO5L0M3PxYU7k2NwZwqpvO0D0awRQZzRaqaZP5a1lNgTyzVhnaR2sPEYI8j5dA1qhPLcYrtDXwQf1wgaVBqBmcjMOO7vmUNnGbhlrV++Etz7V42s0ErlWYTS3eTxxviHm3dC3apOzpKE/jXs6iixDHTfydh2AF1/SVNwvXZQU9cv9B6qC3Eqj20AlzxjKXQ2eUbS2Y8686teQDbcaydQb88PfqUlIwxFFt/Ql3OLA2ikeB6I/Fa/xw+/p2HojnrhhbHIB4hP8RnylHT/AF/itBZ7/zhMj9HuFbAKN1092XVC1LkauhjwXuLtPXTIT+37RVcmas7iGTEfuFVOhdKv9CUfhLveyRMh39JWzVJSFYFcUG46A9kQmWO6dFzdS89cS8I30nN6soet3zrnml51xB6NWXr8gLqZhOqGLe65vNT5DfO9KXw2qVK6qfyiXHnB2CglmUjm8nzaSh7JHrcUELt0Xo9blVVetvsXT6+rvDoc4DIKsAKzl9a+00g3waUzEjlGjYMvFn8+vOGXJNd8dIpSygP80PWV5kLPQTuDCVgEGpDFo+442v4+fy1u2KhyXr04p1wjcfbz7QGJv/mSOhO6tnEotsk3gXmY/gRNT4Rwkc4bT8QpnlIaHwkk7qIUo=
  app: ucla-events
  on:
    repo: mitrikyle/ucla-events
